<?php

/**
 * @file
 * Provides a rusa perm registration entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function rusa_perm_reg_theme() {
	return [ 
    		'rusa_perm_registration' => [
      			'render element' => 'elements',
    		],
    		'rusa_perm_ride_reg' => [
      			'render element' => 'elements',
      			'template' => 'rusa-perm-ride-reg',
    		],
	    ];

}


/**
 * Prepares variables for rusa perm registration templates.
 *
 * Default template: rusa-perm-registration.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the rusa perm registration information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_rusa_perm_registration(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  $variables['attributes']['class'][] = 'perm-prog-reg';
}

function template_preprocess_rusa_perm_ride_reg(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  $variables['attributes']['class'][] = 'perm-ride-reg';
}

/**
 * Implements hook_preprocess_page_title
 *
 * Change page title from the default ID # to something more meaningful
 *
 */
 function rusa_perm_reg_preprocess_page_title(&$variables) {
    if( $entity = \Drupal::request()->attributes->get('rusa_perm_registration')) {
        $owner = $entity->getOwner();
        $variables['title'] = 'Perm Program Registration for ' . $owner->getAccountName(); 
    }
 }


